
## What is Word2Vec-- 
#### It is a word embedding technique to convert words to a set of numbers -By GOOGLE 

### ADVANTAGES:------
#### 1.) Can understand the SEMANTIC MEANING..
#### 2.) Vectors are of lower dimensions as compared to BAG_OF_WORDS and Tf-Idf
#### 3.) Dense Vectors -- mostly have non-zero values ->which helps in reducing Overfitting

#### -->>Deep learning Technique + Probability based Technique not a Frequency based technique




In [4]:

# ### Dataset used - Game of throne books from Kaggle 

import numpy as numpy
import pandas as pd

In [5]:

!pip install gensim

In [6]:

import gensim
import os



In [7]:
# %%
os.listdir('data')



['001ssb.txt', '002ssb.txt', '003ssb.txt', '004ssb.txt', '005ssb.txt']

In [8]:
# %%
material = (os.path.join("data", '003ssb.txt'))
print(material)





data\003ssb.txt


In [9]:
# %% [markdown]
# #### Breaking book corpus in sentences  and then preprocessing it

# %%
import os
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk

nltk.download('punkt')

story = []
for filename in os.listdir('data'):
    file_path = os.path.join('data', filename)
    with open(file_path, 'r', encoding='latin1') as f:  # Replace 'latin1' with the correct encoding if known
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        # print(raw_sent)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))



[nltk_data] Downloading package punkt to C:\Users\Subham
[nltk_data]     Gupta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [10]:

# %%
def find_dimensions(lst):
    outer_dim = len(lst)
    inner_dim = [len(sublist) for sublist in lst] if lst else []
    return outer_dim, inner_dim

# Example list of lists

dimensions = find_dimensions(story)

print("Outer Dimension (Number of sublists):", dimensions[0])
print("Inner Dimensions (Lengths of sublists):", dimensions[1])




Outer Dimension (Number of sublists): 145020
Inner Dimensions (Lengths of sublists): [30, 4, 5, 10, 7, 16, 5, 7, 3, 3, 4, 5, 11, 13, 9, 13, 10, 8, 10, 9, 10, 4, 4, 9, 8, 7, 24, 22, 6, 13, 12, 4, 8, 23, 6, 26, 2, 4, 12, 28, 13, 6, 17, 19, 5, 25, 6, 15, 14, 17, 27, 27, 8, 14, 22, 6, 23, 6, 12, 3, 6, 5, 4, 17, 7, 7, 15, 23, 7, 3, 3, 10, 4, 32, 24, 15, 4, 8, 4, 8, 13, 11, 3, 3, 7, 5, 4, 5, 4, 5, 8, 11, 10, 2, 7, 6, 2, 4, 3, 10, 2, 3, 6, 9, 4, 3, 2, 3, 3, 11, 10, 10, 4, 9, 9, 13, 25, 31, 4, 5, 4, 22, 10, 10, 21, 2, 6, 7, 9, 19, 12, 3, 13, 3, 6, 23, 12, 13, 7, 0, 0, 2, 9, 2, 12, 6, 7, 4, 13, 4, 6, 4, 2, 2, 28, 21, 5, 4, 7, 10, 11, 15, 28, 11, 16, 5, 11, 2, 16, 6, 3, 6, 16, 6, 5, 9, 8, 7, 12, 5, 3, 10, 5, 11, 6, 10, 6, 7, 2, 4, 2, 4, 4, 13, 3, 1, 2, 1, 9, 11, 22, 13, 14, 9, 7, 7, 2, 11, 3, 3, 2, 3, 4, 7, 14, 9, 7, 0, 0, 6, 2, 21, 13, 36, 4, 8, 8, 6, 25, 23, 7, 33, 27, 23, 6, 6, 24, 10, 3, 5, 1, 4, 11, 28, 2, 3, 2, 4, 9, 9, 4, 8, 4, 14, 14, 2, 0, 0, 7, 4, 6, 3, 8, 12, 5, 3, 3, 4, 3, 4, 6, 4, 5

In [11]:
# %%
story



[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [12]:
# %%
print(len(story),len(story[0]))


145020 30


In [13]:

# %%
len(story)


#%%

145020

In [15]:
# %% [markdown]
# #### Building the Word2Vec model using Gensim

# %%
model = gensim.models.Word2Vec(
    window=10, # Prediction of Centre word taking 10 -10 words both the sides
    #Eg:- window = 1  "Hi how are you all good?"
    # """1. Hi how are
    #     2. how are you
    #     3. ae you all
    #     4.you all good"""
    min_count=2, # Choose only those sentences which 2 words atleast
    workers=4   
        )

In [16]:

# %% [markdown]
# #### Building my Vocalulary i.e., all the unique words in my CORPUS

# %%
model.build_vocab(story)

In [17]:

# %%

# Get the number of words in the vocabulary
vocab_size = len(model.wv.key_to_index)

print("Number of words in the vocabulary:", vocab_size)

Number of words in the vocabulary: 17453


In [18]:

# %%
model.corpus_count


145020

In [19]:

# %%
# DEfaukt epoch = 5

model.train(story,
            total_examples = model.corpus_count, # No of sentences in the whole corpus
            epochs = model.epochs) # Default epochs = 5


(6570209, 8628190)

In [20]:

# %%
model.wv.most_similar("daenerys")

[('stormborn', 0.7936449646949768),
 ('targaryen', 0.7413216829299927),
 ('myrcella', 0.7308242917060852),
 ('unburnt', 0.7231053709983826),
 ('princess', 0.7062404155731201),
 ('queen', 0.7003157734870911),
 ('viserys', 0.6892796158790588),
 ('dorne', 0.6665322184562683),
 ('prince', 0.6481955647468567),
 ('khaleesi', 0.6463779807090759)]

In [21]:


# %%
model.wv.most_similar("is")

[('am', 0.7676551342010498),
 ('knows', 0.711094081401825),
 ('isn', 0.6606931686401367),
 ('takes', 0.625376284122467),
 ('seems', 0.6249816417694092),
 ('says', 0.6163857579231262),
 ('means', 0.6124825477600098),
 ('does', 0.6122196316719055),
 ('goes', 0.6086151599884033),
 ('makes', 0.6045132279396057)]

In [22]:



# %% [markdown]
# #### Find odd one out

# %%
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])
# As 'jon' was Adopted

'jon'

In [23]:



# %%
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])


'bronn'

In [24]:

# %% [markdown]
# #### For Vector embedding of a Particular word

# %%
model.wv['jon']

array([-1.4480723 , -0.77377695, -0.48162904, -2.1081164 ,  0.68860775,
        1.0541692 ,  1.3058218 , -1.5263679 , -1.3600117 ,  0.4368491 ,
       -0.78725064, -0.23768395, -0.05247577, -1.0141183 ,  0.12791415,
       -0.10956278,  1.2883177 ,  4.245315  , -0.25191462, -0.52173597,
        1.5590851 , -1.268628  , -0.18846549,  0.94681704, -0.01538264,
       -0.88690346, -0.08362677,  0.43118003, -0.12758243, -0.4618975 ,
       -1.7146949 , -0.81982553,  0.73227775, -0.53758323,  1.2656322 ,
        0.58147085,  1.8247575 ,  0.07938007,  1.8623617 , -0.7633581 ,
       -0.7089238 , -2.1088443 ,  1.1961006 ,  0.8483357 ,  1.1689082 ,
       -1.5003232 , -0.17947061,  0.7430608 , -1.2533875 , -0.41109315,
        0.22962017, -0.01993698,  1.3789628 , -1.3266295 ,  0.21209776,
        0.05497559, -1.1662045 , -1.6519436 ,  1.1145452 , -0.198607  ,
        0.8980363 ,  1.2606051 ,  1.5081615 , -1.523266  ,  1.2616779 ,
       -0.7893246 ,  0.29709125,  2.8504634 , -0.80466586,  0.63

In [25]:



# %% [markdown]
# ### Similarity Function

# %%
model.wv.similarity('arya','sansa') # As they are sisters

# %%
model.wv.similarity('cersei','sansa') # As they are sisters

# %%
model.wv.similarity('tywin','sansa') # As they are  not relatedsisters

# %% [markdown]
# #### Vector represntations of all the words together

# %%

0.28670353

In [26]:

model.wv.get_normed_vectors()


array([[-0.19761789,  0.06662414,  0.2022624 , ..., -0.19180538,
        -0.03887307,  0.05308583],
       [-0.02283674, -0.07342411,  0.2590726 , ..., -0.10973782,
        -0.02664435, -0.0073191 ],
       [ 0.17528138,  0.02628191, -0.07212457, ...,  0.04801043,
         0.0677614 , -0.04446188],
       ...,
       [ 0.04324504,  0.07004726,  0.04644896, ..., -0.10680263,
         0.0621419 , -0.08003046],
       [ 0.02165331,  0.01715414,  0.15477012, ..., -0.0392054 ,
         0.13070954, -0.05510257],
       [-0.0977499 ,  0.11435311,  0.08862305, ..., -0.1002098 ,
         0.09400025, -0.06648798]], dtype=float32)

In [27]:
# %%
model.wv.get_normed_vectors().shape 
# Unique words = 17453
# 100 implies dimension of each Vector

# %% [markdown]
# #### To check that the 1st vector belongs to which word

# %%

(17453, 100)

In [28]:

y = model.wv.index_to_key


In [29]:
# %%
len(y), y # Note we haven't removed the StopWords

(17453,
 ['the',
  'and',
  'to',
  'of',
  'he',
  'his',
  'was',
  'you',
  'her',
  'in',
  'it',
  'had',
  'that',
  'she',
  'as',
  'with',
  'him',
  'not',
  'but',
  'for',
  'they',
  'is',
  'at',
  'on',
  'said',
  'my',
  'have',
  'be',
  'lord',
  'them',
  'no',
  'from',
  'would',
  'were',
  'me',
  'your',
  'one',
  'all',
  'when',
  'will',
  'ser',
  'if',
  'so',
  'their',
  'we',
  'could',
  'are',
  'man',
  'there',
  'this',
  'up',
  'been',
  'what',
  'did',
  'by',
  'king',
  'do',
  'men',
  'back',
  'out',
  'more',
  'or',
  'who',
  'down',
  'well',
  'than',
  'only',
  'like',
  'jon',
  'some',
  'father',
  'old',
  'hand',
  'even',
  'too',
  'tyrion',
  'before',
  'never',
  'an',
  'off',
  'see',
  'know',
  'into',
  'made',
  'now',
  'eyes',
  'black',
  'told',
  'lady',
  'thought',
  'time',
  'then',
  'how',
  'long',
  'has',
  'can',
  'might',
  'us',
  'come',
  'where',
  'here',
  'through',
  'still',
  'face',
  'he

In [30]:

# %%
model.wv['tyrion']


array([-0.43219593,  0.29344365, -0.31050378, -1.2835474 ,  1.4733909 ,
       -0.03480479,  0.9956894 , -0.13912582, -0.96298623,  1.03797   ,
        0.7389104 ,  1.1035334 ,  0.76118255, -2.0133426 ,  0.29712215,
       -2.106652  ,  0.00933682,  1.5547464 ,  0.12823057,  0.8165278 ,
        0.38645396, -1.0631707 ,  1.4386436 , -1.7433952 ,  1.1084465 ,
        0.9379347 , -0.42963144, -0.40550384, -1.8066425 , -0.81082827,
       -0.7550563 , -0.82432115,  0.102189  , -1.0712084 ,  2.303538  ,
       -1.0436549 , -0.8820662 , -0.19990341,  0.2045571 , -1.4240055 ,
       -0.5239707 , -2.3150795 ,  0.09495564,  1.3677269 ,  0.13738565,
       -3.3850768 , -0.7871595 ,  0.3626323 , -0.8057242 ,  0.20803905,
        0.9512838 , -0.09560054,  0.0923854 ,  0.14399515, -0.5998671 ,
        0.42199597, -1.4827516 , -0.49817973,  0.9779744 , -1.3536465 ,
        0.31359917,  0.5733079 ,  1.2491124 , -1.8201152 , -0.28078622,
        0.61656535,  1.1604829 ,  1.463632  , -0.8977178 , -0.07

In [31]:




# %% [markdown]
# ### Applying PCA to visualize the WORDS 

# %% [markdown]
# #### ------------Reducing the DIMENSIONS of the Words

# %%
from sklearn.decomposition import PCA    

# %%
pca = PCA(n_components=3)

# %%
X = pca.fit_transform(model.wv.get_normed_vectors()) # Passing the 2D array of all the Words

# %%
X[:5]

# %% [markdown]
# #### Shows Dimenion Reduction

array([[ 0.16307199,  0.58068705, -0.05199437],
       [ 0.17166606,  0.35397986,  0.01744792],
       [-0.30051297,  0.55905104,  0.24757463],
       [ 0.01182047,  0.37409753, -0.1343288 ],
       [-0.10086166,  0.5513222 ,  0.2933535 ]], dtype=float32)

In [32]:
# %%
X.shape


(17453, 3)

In [33]:



# %%
# Plotting the 1st 100 Frequent Words
import plotly.express as px
fig = px.scatter_3d(X[:100], x=0,y=2,z=2, color =y[:100])
fig.show()




In [34]:

# %%
# Plotting the 1st 100 Frequent Words
import plotly.express as px
fig = px.scatter_3d(X[200:300], x=0,y=2,z=2, color =y[:100])
fig.show()

# %%

In [35]:

# %% [markdown]
# ### Glove
# 

# %%
import gensim.downloader as api

# Load pre-trained GloVe model
glove = api.load("glove-wiki-gigaword-50")  # 50-dimensional embeddings

# Get vector for a word
vector = glove["sample"]
print(vector)

# Most similar words
print(glove.most_similar("sample"))




[ 0.35128   0.039497  0.35241   0.032418  0.80215   0.42617  -0.17973
 -0.27992   1.2916    0.58453   0.67246  -0.70163   1.045     0.12725
  0.69075  -0.05367  -0.18499  -0.7518   -0.5047   -1.3139    0.15445
 -0.10888   1.51      0.45995   0.20452  -0.070016 -1.022     0.46685
 -0.24834  -0.39889   2.0959   -0.68636  -0.41756  -0.84522   0.59551
 -0.17554   0.87743   0.80909   0.32158   0.20119   0.9452    0.11658
 -0.1507    0.42317  -0.30518  -0.27963   0.76269   0.54631   0.17827
 -0.081607]
[('samples', 0.882198691368103), ('sampling', 0.8172192573547363), ('urine', 0.7463781237602234), ('measurements', 0.7384749054908752), ('accurate', 0.70806485414505), ('dna', 0.7061437368392944), ('random', 0.7039097547531128), ('analyzed', 0.7004671096801758), ('containing', 0.6847900748252869), ('contained', 0.6807035207748413)]
